catalog:
  '@antfu/eslint-config': ^4.11.0
  '@tsconfig/node20': ^20.1.5
  '@types/dotenv-parse-variables': ^2.0.3
  '@types/node': ^22.13.14
  dotenv-flow: ^4.1.0
  dotenv-parse-variables: ^2.0.0
  esbuild: ^0.25.1
  eslint: ^9.23.0
  tsx: ^4.19.3
  typescript: ^5.8.2
